# Generated by Django 2.2.1 on 2019-10-10 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/hairdresser'),
            preserve_default=False,
        ),
    ]
