# Generated by Django 2.2.1 on 2019-10-17 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hairdresser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('appointment_time', models.CharField(choices=[('0', '08:00'), ('1', '09:00'), ('2', '10:00'), ('3', '11:00'), ('4', '12:00'), ('5', '14:00')], max_length=1)),
                ('description', models.TextField()),
                ('hairdresser_id', models.ManyToManyField(to='hairdresser.Hairdresser')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
