# Generated by Django 2.2.1 on 2019-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
    ]
