# Generated by Django 2.2.1 on 2019-10-10 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191010_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_time',
            field=models.CharField(choices=[('0', '08:00'), ('1', '09:00'), ('2', '10:00'), ('3', '11:00'), ('4', '12:00'), ('5', '14:00')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
