# Generated by Django 2.2.1 on 2019-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0004_auto_20191010_1428'),
        ('order', '0003_order_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hairdresser_id',
        ),
        migrations.AddField(
            model_name='order',
            name='hairdresser_id',
            field=models.ManyToManyField(to='hairdresser.Hairdresser'),
        ),
    ]
