# Generated by Django 2.2.1 on 2019-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='loyalty_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
